### ISSUE TITLE
BUG: The 25mm / 18mm version is actually 29 / 20!

### ISSUE THREAD

**Issue by Googliola** [V1EngineeringInc/ZenXY-v2#3]

**Comment by Googliola** [comment]
Just to be clear, I used the files from https://github.com/V1EngineeringInc/ZenXY-v2/tree/main/25mm_18mm/25%2018

- Cross corner diameter is 25.2mm

![image](https://user-images.githubusercontent.com/505490/218270771-64cd405a-8348-434e-94d0-ca540a0b712d.png)

- Power corner 2 diameter is 23mm and 25.2mm
Power corner main same as Power corner 2 (23mm and 25.2mm)
![image](https://user-images.githubusercontent.com/505490/218270790-d9fa8021-9de5-4c1c-bcb6-a455aea5d65d.png)
![image](https://user-images.githubusercontent.com/505490/218270816-e7f7fcd4-2248-4612-a6e0-65fd3f25ca73.png)

- Trucks are 29mm and 18.4mm

![image](https://user-images.githubusercontent.com/505490/218270852-49ea39f4-adee-4ba6-a724-f4cc84b962c6.png)
![image](https://user-images.githubusercontent.com/505490/218270873-1c6b0678-f641-46e3-802f-ca8d727c35f9.png)

- Zen Center is 21mm  -> OK for 20mm tubes, which should be available in "metric" stores

**Comment by V1EngineeringInc** [comment]
You also have comments at printables. I have asked you or emt diameter there twice. Please choose one place to have a conversation.

Short and sweet to your questions, there is an interference fit built in. There are clearances, and wheels involved. So your analysis doesn't make much sense. 14.5mm ID of the center part means nothing, that gets wheels.

Did you try to assemble this or are you just concerned about your measurements?

Support is preferred in the V1E.com forums. Please move the conversation there. There very well could be a issue but at this point more than a year in I have doubts. I sell a lot of Zen kits domestic an international.
